pipeline{
    agent any

    stages {

        stage("Set Variable") {
            steps {
                script {
                    SSH_CONNECTION = "ubuntu@j8b104.p.ssafy.io"
                    CONTAINER_NAME = "dodo-fastapi"
                    IMAGE_NAME = "eello/dodo-fastapi"
                    PROJECT_PATH = "./be/python/fastapi"
                }
            }
        }

        stage('Docker build image') {
            steps {
                dir("${PROJECT_PATH}") {
                    sh 'pwd'
                    sh 'ls'
                    sh 'ls ../resources'
                    sh 'cp ../resources/db-application.json ./app/database/db-application.json'
                    sh 'ls ./app'
                    sh "docker build --no-cache -t eello/dodo-fastapi:latest ."
                }
            }
        }

        stage('Docker push image') {
            steps {
                withCredentials([string(credentialsId: 'dockerHubPwd', variable: 'dockerHubPwd')]) {
                    sh "docker login -u eello -p ${dockerHubPwd}"
                }
                sh "docker push ${IMAGE_NAME}"
            }

            post {
                success {
                    echo 'success'
                }

                failure {
                    echo 'failed'
                }
            }
        }

        stage('Run Container on SSH Dev Server') {
            steps {
                echo 'SSH'
                sshagent (credentials: ['ssh-agent']) {
//                     sh "ssh -o StrictHostKeyChecking=no ${SSH_CONNECTION} 'whoami'"
//                     sh "ssh -o StrictHostKeyChecking=no ${SSH_CONNECTION} 'docker ps -q --filter name=${CONTAINER_NAME} | grep -q . && docker rm -f \$(docker ps -aq --filter name=${CONTAINER_NAME})'"
                    sh "ssh -o StrictHostKeyChecking=no ${SSH_CONNECTION} 'docker rm -f ${CONTAINER_NAME}'"
                    sh "ssh -o StrictHostKeyChecking=no ${SSH_CONNECTION} 'docker rmi -f ${IMAGE_NAME}'"
                    sh "ssh -o StrictHostKeyChecking=no ${SSH_CONNECTION} 'docker pull ${IMAGE_NAME}:latest'"
                    sh "ssh -o StrictHostKeyChecking=no ${SSH_CONNECTION} 'docker run -d --name ${CONTAINER_NAME} -p 8000:8000 ${IMAGE_NAME}'"
                }

            }

        }

    }
}
